package com.bcptecnologias.migracao.gestortributario.negocio.gestor;

public enum TabelaCpTrib {
	TAB_CONTRIBUINTE("TAB_CONTRIBUINTE"),
	TAB_IMOVEL("TAB_IMOVEL"),
	TAB_DETALHE_IMOVEL("TAB_DETALHE_IMOVEL"),
	TAB_AIDF("TAB_AIDF"),
	TAB_ALVARA_IMPRESSO("TAB_ALVARA_IMPRESSO"),
	TAB_ATIVIDADE_SECUNDARIA("TAB_ATIVIDADE_SECUNDARIA"),
	TAB_ATIVIDADE_VALOR_TRIBUTOS("TAB_ATIVIDADE_VALOR_TRIBUTOS"),
	TAB_CERTIDAO_NEGATIVA("TAB_CERTIDAO_NEGATIVA"),
	TAB_CONTRIBUINTE_HISTORICO("Tab_Contribuinte_Historico"),
	Tab_CONTA_CONTRIBUINTE("Tab_Conta_Contribuinte"),
	TAB_COTAS_PARCELAMENTO("TAB_COTAS_PARCELAMENTO"),
	TAB_DECLARACAO_CONTRIBUINTE("TAB_DECLARACAO_CONTRIBUINTE"),
	TAB_DETALHE_DECLARACAO("TAB_DETALHE_DECLARACAO"),
	TAB_DETALHE_IMOVEL_HISTORICO("TAB_DETALHE_IMOVEL_HISTORICO"),
	TAB_DETALHE_OBRIGACAO("TAB_DETALHE_OBRIGACAO"),
	TAB_GERACAO_TRIBUTO("Tab_Geracao_Tributo"),
	TAB_IMOVEL_HISTORICO("Tab_IMOVEL_HISTORICO"),
	TAB_ITEM_NOTA_AVULSA("Tab_ITEM_NOTA_AVULSA"),
	TAB_LOG_OCORRENCIA("TAB_LOG_OCORRENCIA"),
	TAB_LOTE_PAGAMENTO("TAB_LOTE_PAGAMENTO"),
	TAB_NOTA_AVULSA("Tab_Nota_Avulsa"),
	TAB_OBRIGACAO_CONTRIBUINTE("TAB_OBRIGACAO_CONTRIBUINTE"),
	TAB_PAGAMENTO_EXTRATO("TAB_PAGAMENTO_EXTRATO"),
	TAB_TRANSFERENCIA_IMOVEL("TAB_TRANSFERENCIA_IMOVEL"),
	TAB_TRANSPORTADOR_VEICULO("TAB_TRANSPORTADOR_VEICULO"),
	TAB_USUARIO_ACESSO("TAB_USUARIO_ACESSO"),
	TAB_NUM_CORRELATIVO("Tab_Num_Correlativo"),
	TAB_PARCELAMENTO("Tab_Parcelamento"),
	;
	private String nome;
	TabelaCpTrib(String nome){
		this.nome=nome;
	}
	public String getNome(){
		return nome;
	}
}
