insert into TAB_CONTRIBUINTE
SELECT NULL,MOBIL_CODIGO,MOBIL_COD_CONTRIBUINTE,MOBIL_CNPJ,MOBIL_NOME_RAZAO,MOBIL_NOME_FANTASIA,
MOBIL_TIPO_LOGRADOURO,MOBIL_NOME_LOGRA,MOBIL_NUM_LOGRA,MOBIL_COMP_LOGRA,MOBIL_NOME_BAIR,
MOBIL_CEP,MOBIL_MUNICIPIO,MOBIL_UF,convert(smalldatetime,GETDATE(),103),
convert(smalldatetime,GETDATE(),103),1,'MIGRACAO',NULL,NULL,MOBIL_COD_NAT_JURID,
MOBIL_COD_ATIVIDADE1,NULL,MOBIL_ESTABELECIDO,NULL,NULL,1,MOBIL_INSC_ESTADUAL,NULL,1,NULL,
MOBIL_QTE_EMPREGADOS,1,NULL,NULL,MOBIL_COD_NIVEL_TECNICO,NULL,NULL,1,NULL,NULL,MOBIL_FAX,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,1,NULL,NULL,MOBIL_TELEFONE,MOBIL_E_MAIL,NULL
 FROM IMPORT..Empresas$


